#ifndef MASTER_COMMAND_H
#define MASTER_COMMAND_H

#include "../ADT/master_header_adt.h"
#include "LOGIN/LOGIN.h"
#include "HELP/HELP.h"
#include "WORK/work.h"
#include "LOAD/LOAD.h"
#include "LOGOUT/LOGOUT.h"
#include "QUANTUM/quantum.h"
#include "REGISTER/REGISTER.h"
#include "SAVE/SAVE.h"
#include "START/START.h"
#include "STORE_LIST/store_list.h"
#include "STORE_REMOVE/store_remove.h"
#include "STORE_REQUEST/store_request.h"
#include "STORE_SUPPLY/store_supply.h"
#include "TEBAKANGKA/tebakangka.h"
#include "WORDL3/wordl3.h"
#include "WORK_CHALLENGE/work_challenge.h"
#include "CART_ADD/CART_ADD.h"
#include "CART_PAY/CART_PAY.h"
#include "CART_REMOVE/CART_REMOVE.h"
#include "CART_SHOW/CART_SHOW.h"
#include "HISTORY/HISTORY.h"
#include "PROFILE/PROFILE.h"
#include "WISHLIST_ADD/WISHLIST_ADD.h"
#include "WISHLIST_CLEAR/WISHLIST_CLEAR.h"
#include "WISHLIST_REMOVE_1/WISHLIST_REMOVE_1.h"
#include "WISHLIST_REMOVE_2/WISHLIST_REMOVE_2.h"
#include "WISHLIST_SHOW/WISHLIST_SHOW.h"
#include "WISHLIST_SWAP/WISHLIST_SWAP.h"
#include "BIOWEAPON/BIOWEAPON.h"
#include "OPTIMASIRUTE/OPTIMASIRUTE.h"
#include "GLOBALALIGNMENT/GLOBALALIGNMENT.h"


#endif 